# Generated by Django 4.0.3 on 2022-03-17 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='il',
            new_name='ct',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='yourChoice',
            field=models.BooleanField(default=False),
        ),
    ]
